// <auto-generated />
using AutosABC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AutosABC.Migrations
{
    [DbContext(typeof(AutosABCContext))]
    partial class AutosABCContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AutosABC.Models.Auto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Color");

                    b.Property<string>("DescripcionEstetica");

                    b.Property<string>("Folio");

                    b.Property<string>("Marca");

                    b.Property<string>("Modelo");

                    b.Property<int>("SolicitudID");

                    b.Property<string>("TipoTransmision");

                    b.HasKey("ID");

                    b.HasIndex("SolicitudID");

                    b.ToTable("Auto");
                });

            modelBuilder.Entity("AutosABC.Models.Solicitud", b =>
                {
                    b.Property<int>("SolicitudID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Fecha");

                    b.Property<int>("NumeroLote");

                    b.HasKey("SolicitudID");

                    b.ToTable("Solicitud");
                });

            modelBuilder.Entity("AutosABC.Models.Auto", b =>
                {
                    b.HasOne("AutosABC.Models.Solicitud", "Solicitud")
                        .WithMany("Autos")
                        .HasForeignKey("SolicitudID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
